/**
 * Tactical CAD (Cut the Cake) - Milestone 1A Telemetry Playback Engine
 * 
 * Strict boundary:
 * - Browser is a dumb renderer for scientific telemetry.
 * - Does NOT calculate tactical margins, does NOT raycast, does NOT repair geometry.
 * - Renders authoritative 35 Hz per-tic states generated by the frozen Python scientific core.
 */

// State
let manifest = null;
let currentMode = 'broken'; // 'broken' | 'repaired'
let currentTic = 0;
let isPlaying = false;
let playbackSpeed = 1.0;
let animTimer = null;

// DOM Elements
const canvas = document.getElementById('mapCanvas');
const ctx = canvas.getContext('2d');
const viewportContainer = document.getElementById('viewportContainer');

const btnModeBroken = document.getElementById('btnModeBroken');
const btnModeRepaired = document.getElementById('btnModeRepaired');
const btnPlayPause = document.getElementById('btnPlayPause');
const btnStepBack = document.getElementById('btnStepBack');
const btnStepFwd = document.getElementById('btnStepFwd');
const btnReset = document.getElementById('btnReset');
const btnSpeed05 = document.getElementById('btnSpeed05');
const btnSpeed10 = document.getElementById('btnSpeed10');
const btnSpeed20 = document.getElementById('btnSpeed20');

const timelineScrubber = document.getElementById('timelineScrubber');
const timelineProgress = document.getElementById('timelineProgress');
const timelineHead = document.getElementById('timelineHead');
const eventMarkerLayer = document.getElementById('eventMarkerLayer');

const readoutTic = document.getElementById('readoutTic');
const readoutTotalTics = document.getElementById('readoutTotalTics');
const readoutTime = document.getElementById('readoutTime');
const readoutTotalTime = document.getElementById('readoutTotalTime');

const fixtureBadge = document.getElementById('fixtureBadge');
const evidenceBadge = document.getElementById('evidenceBadge');
const verdictBadge = document.getElementById('verdictBadge');
const valMargin = document.getElementById('valMargin');
const valMarginMs = document.getElementById('valMarginMs');
const valLStar = document.getElementById('valLStar');
const valEngineStatus = document.getElementById('valEngineStatus');
const controllerStateBadge = document.getElementById('controllerStateBadge');
const valActiveTarget = document.getElementById('valActiveTarget');
const valRouteDist = document.getElementById('valRouteDist');

const threatListContainer = document.getElementById('threatListContainer');
const whyCard = document.getElementById('whyCard');
const whyText = document.getElementById('whyText');
const repairCard = document.getElementById('repairCard');
const repairText = document.getElementById('repairText');

const tagPlayerPos = document.getElementById('tagPlayerPos');
const tagReticle = document.getElementById('tagReticle');
const tagLOS = document.getElementById('tagLOS');

// Coordinate Transformation (Meters -> Canvas Pixels)
let viewTransform = {
  scale: 60, // pixels per meter
  offsetX: 80,
  offsetY: 250,
  widthM: 10,
  heightM: 6
};

// Initialize Application
async function init() {
  try {
    if (window.SCENE_MANIFEST) {
      manifest = window.SCENE_MANIFEST;
    } else {
      const resp = await fetch('../data/m1_scene.json');
      manifest = await resp.json();
    }
    setupUI();
    setupCanvas();
    renderTimelineEvents();
    updateView(0);
  } catch (err) {
    console.error('Failed to load scene manifest:', err);
    alert('Failed to load Tactical CAD scene manifest: ' + err.message);
  }
}

function getScenario() {
  return currentMode === 'broken' ? manifest.broken_scenario : manifest.repaired_scenario;
}

function getObstacles() {
  if (currentMode === 'broken') {
    return manifest.geometry.obstacles;
  } else {
    // In repaired mode, obstacle 0 is shifted by the repair operator
    const repair = manifest.repair;
    return manifest.geometry.obstacles.map(obs => {
      if (obs.obstacle_id === repair.obstacle_id) {
        const dx = repair.direction[0] * repair.displacement_m;
        const dy = repair.direction[1] * repair.displacement_m;
        return {
          obstacle_id: obs.obstacle_id,
          vertices: obs.vertices.map(([x, y]) => [x + dx, y + dy])
        };
      }
      return obs;
    });
  }
}

function setupUI() {
  fixtureBadge.textContent = manifest.provenance.fixture_id;
  evidenceBadge.textContent = manifest.provenance.evidence_tier === 'native_engine_verified'
    ? 'FROZEN EVIDENCE: SOURCE + VIZDOOM VERIFIED'
    : 'SOURCE MODEL VERIFIED';

  readoutTotalTics.textContent = manifest.clock.total_tics;
  readoutTotalTime.textContent = manifest.clock.total_duration_s.toFixed(2) + 's';

  // Mode Toggle Events
  btnModeBroken.addEventListener('click', () => switchMode('broken'));
  btnModeRepaired.addEventListener('click', () => switchMode('repaired'));

  // Playback Controls
  btnPlayPause.addEventListener('click', togglePlay);
  btnStepBack.addEventListener('click', () => stepTic(-1));
  btnStepFwd.addEventListener('click', () => stepTic(1));
  btnReset.addEventListener('click', () => setTic(0));

  // Speed Controls
  btnSpeed05.addEventListener('click', () => setSpeed(0.5, btnSpeed05));
  btnSpeed10.addEventListener('click', () => setSpeed(1.0, btnSpeed10));
  btnSpeed20.addEventListener('click', () => setSpeed(2.0, btnSpeed20));

  // Timeline Scrubbing
  timelineScrubber.addEventListener('click', (e) => {
    const rect = timelineScrubber.getBoundingClientRect();
    const ratio = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
    const targetTic = Math.round(ratio * manifest.clock.total_tics);
    setTic(targetTic);
  });

  window.addEventListener('resize', resizeCanvas);
}

function switchMode(mode) {
  currentMode = mode;
  if (mode === 'broken') {
    btnModeBroken.className = 'toggle-btn active broken';
    btnModeRepaired.className = 'toggle-btn';
    repairCard.style.display = 'none';
    whyCard.style.display = 'block';
  } else {
    btnModeBroken.className = 'toggle-btn';
    btnModeRepaired.className = 'toggle-btn active repaired';
    repairCard.style.display = 'block';
    whyCard.style.display = 'none';
  }
  renderTimelineEvents();
  updateView(currentTic);
}

function setSpeed(speed, activeBtn) {
  playbackSpeed = speed;
  [btnSpeed05, btnSpeed10, btnSpeed20].forEach(b => b.style.background = '#172130');
  activeBtn.style.background = '#233145';
  if (isPlaying) {
    pause();
    play();
  }
}

function togglePlay() {
  if (isPlaying) {
    pause();
  } else {
    play();
  }
}

function play() {
  const scenario = getScenario();
  if (currentTic >= scenario.telemetry_frames.length - 1) {
    currentTic = 0;
  }
  isPlaying = true;
  btnPlayPause.textContent = '⏸ Pause';
  btnPlayPause.classList.remove('primary');
  btnPlayPause.style.background = 'var(--amber)';

  const intervalMs = (1000.0 / manifest.clock.ticrate_hz) / playbackSpeed;
  animTimer = setInterval(() => {
    if (currentTic < scenario.telemetry_frames.length - 1) {
      setTic(currentTic + 1);
    } else {
      pause();
    }
  }, intervalMs);
}

function pause() {
  isPlaying = false;
  clearInterval(animTimer);
  btnPlayPause.textContent = '▶ Play';
  btnPlayPause.classList.add('primary');
  btnPlayPause.style.background = '';
}

function stepTic(delta) {
  pause();
  const scenario = getScenario();
  const maxTic = scenario.telemetry_frames.length - 1;
  const nextTic = Math.max(0, Math.min(maxTic, currentTic + delta));
  setTic(nextTic);
}

function setTic(tic) {
  currentTic = tic;
  updateView(tic);
}

function setupCanvas() {
  resizeCanvas();
}

function resizeCanvas() {
  const rect = viewportContainer.getBoundingClientRect();
  canvas.width = rect.width - 20;
  canvas.height = rect.height - 20;
  
  // Arena is 10m x 6m (X: [0, 10], Y: [-3, 3])
  const padding = 50;
  const scaleX = (canvas.width - padding * 2) / 10.5;
  const scaleY = (canvas.height - padding * 2) / 6.5;
  viewTransform.scale = Math.min(scaleX, scaleY);
  
  viewTransform.offsetX = padding + 15;
  viewTransform.offsetY = canvas.height / 2;
  
  drawMap();
}

// Convert arena coordinates (m) to canvas pixels
function toCanvasX(x) {
  return viewTransform.offsetX + x * viewTransform.scale;
}

function toCanvasY(y) {
  // Arena +y is up, canvas +y is down
  return viewTransform.offsetY - y * viewTransform.scale;
}

// Render Timeline Events
function renderTimelineEvents() {
  eventMarkerLayer.innerHTML = '';
  const scenario = getScenario();
  const totalTics = manifest.clock.total_tics;

  scenario.events.forEach(evt => {
    const marker = document.createElement('div');
    marker.className = 'event-marker ' + evt.type.toLowerCase().replace('_', '-');
    const pct = (evt.tic / totalTics) * 100;
    marker.style.left = `${pct}%`;
    marker.title = `[Tic ${evt.tic} / ${evt.time_s}s] ${evt.type}: ${evt.description}`;
    marker.addEventListener('click', (e) => {
      e.stopPropagation();
      setTic(evt.tic);
    });
    eventMarkerLayer.appendChild(marker);
  });
}

// Main View Update
function updateView(tic) {
  const scenario = getScenario();
  const frames = scenario.telemetry_frames;
  const frame = frames[Math.min(tic, frames.length - 1)];

  // Update Timeline Scrubber
  const totalTics = manifest.clock.total_tics;
  const progressPct = (frame.tic / totalTics) * 100;
  timelineProgress.style.width = `${progressPct}%`;
  timelineHead.style.left = `${progressPct}%`;

  // Update Header Readouts
  readoutTic.textContent = frame.tic;
  readoutTime.textContent = frame.time_s.toFixed(2) + 's';

  // Update Sidebar
  if (currentMode === 'broken') {
    verdictBadge.textContent = 'UNSERVICEABLE';
    verdictBadge.className = 'badge';
    verdictBadge.style.color = 'var(--red)';
    verdictBadge.style.borderColor = 'rgba(248, 81, 73, 0.4)';
    
    valMargin.textContent = `${scenario.tactical_margin_tics} tics`;
    valMargin.className = 'margin-val status-unserviceable';
    valMarginMs.textContent = `${scenario.tactical_margin_ms} ms`;
    valMarginMs.className = 'margin-status status-unserviceable';
    
    valLStar.textContent = `+${scenario.l_star_tics} tics`;
    valEngineStatus.textContent = `Fatal Death at Tic ${scenario.death_tic} (0 HP)`;
    valEngineStatus.style.color = 'var(--red)';
  } else {
    verdictBadge.textContent = 'SERVICEABLE';
    verdictBadge.className = 'badge verified';
    
    valMargin.textContent = `+${scenario.tactical_margin_tics} tics`;
    valMargin.className = 'margin-val status-serviceable';
    valMarginMs.textContent = `+${scenario.tactical_margin_ms} ms`;
    valMarginMs.className = 'margin-status status-serviceable';
    
    valLStar.textContent = `${scenario.l_star_tics} tics (On Time)`;
    valEngineStatus.textContent = `100% Survival Rescued (100 HP)`;
    valEngineStatus.style.color = 'var(--green)';
  }

  // Controller State
  controllerStateBadge.textContent = frame.controller_state;
  if (frame.controller_state === 'DEAD') {
    controllerStateBadge.style.background = 'rgba(248, 81, 73, 0.2)';
    controllerStateBadge.style.color = 'var(--red)';
  } else if (frame.controller_state === 'CLEARED') {
    controllerStateBadge.style.background = 'rgba(63, 185, 80, 0.2)';
    controllerStateBadge.style.color = 'var(--green)';
  } else if (frame.controller_state === 'SERVICING') {
    controllerStateBadge.style.background = 'rgba(210, 153, 34, 0.2)';
    controllerStateBadge.style.color = 'var(--amber)';
  } else {
    controllerStateBadge.style.background = '#172030';
    controllerStateBadge.style.color = 'var(--blue)';
  }

  valActiveTarget.textContent = frame.active_target_id ? frame.active_target_id : 'None';
  valRouteDist.textContent = `${frame.route_dist_m.toFixed(2)} m / 10.00 m`;

  // Overlay Tags
  tagPlayerPos.textContent = `POS: (${frame.player_pos[0].toFixed(2)}m, ${frame.player_pos[1].toFixed(2)}m)`;
  tagReticle.textContent = `RETICLE: ${frame.reticle_heading_deg.toFixed(1)}° (FWD: ${frame.forward_heading_deg.toFixed(1)}°)`;
  tagLOS.textContent = `VISIBLE: ${frame.visible_threat_ids.length} [${frame.visible_threat_ids.join(', ')}]`;

  // Threats List
  renderThreatList(frame);

  // Diagnostic Cards
  if (scenario.diagnostic) {
    whyText.textContent = scenario.diagnostic.explanation;
  }
  if (manifest.repair) {
    repairText.textContent = `${manifest.repair.description} (Shift: ${manifest.repair.displacement_m.toFixed(2)}m, Invariants Validated: ${manifest.repair.preservation_validated ? 'YES' : 'NO'}).`;
  }

  // Render Map Canvas
  drawMap(frame);
}

function renderThreatList(currentFrame) {
  const scenario = getScenario();
  threatListContainer.innerHTML = '';

  scenario.threat_jobs.forEach(job => {
    const isVisible = currentFrame.visible_threat_ids.includes(job.id);
    const isTarget = currentFrame.active_target_id === job.id;
    const isCleared = currentFrame.tic >= job.completion_tic && scenario.engine_survived;
    const isBreached = currentFrame.tic >= job.deadline_tic && !isCleared;

    let statusTag = 'Occluded';
    let statusColor = 'var(--text-muted)';
    if (isCleared) {
      statusTag = `Neutralized (Tic ${job.completion_tic})`;
      statusColor = 'var(--green)';
    } else if (isBreached) {
      statusTag = `BREACHED (+${job.lateness_tics} tics)`;
      statusColor = 'var(--red)';
    } else if (isTarget && currentFrame.controller_state === 'SERVICING') {
      statusTag = 'ENGAGING / FIRING';
      statusColor = 'var(--amber)';
    } else if (isTarget) {
      statusTag = 'ACQUIRING / AIMING';
      statusColor = 'var(--blue)';
    } else if (isVisible) {
      statusTag = `Revealed (Due Tic ${job.deadline_tic})`;
      statusColor = 'var(--blue)';
    }

    const item = document.createElement('div');
    item.className = 'threat-item';
    item.innerHTML = `
      <div>
        <div class="threat-name">
          <div class="threat-pill" style="background: ${statusColor};"></div>
          <span>${job.id}</span>
        </div>
        <div class="threat-timing">
          Reveal: r=${job.reveal_tic} | Deadline: D=${job.deadline_tic} | Angle: ${job.angle_deg}°
        </div>
      </div>
      <div class="threat-status-tag" style="color: ${statusColor};">${statusTag}</div>
    `;
    threatListContainer.appendChild(item);
  });
}

// 2D Canvas Map Drawing
function drawMap(frame) {
  if (!manifest) return;
  const currentFrame = frame || getScenario().telemetry_frames[Math.min(currentTic, getScenario().telemetry_frames.length - 1)];

  ctx.clearRect(0, 0, canvas.width, canvas.height);

  // 1. Draw Grid in Meters
  ctx.strokeStyle = '#121926';
  ctx.lineWidth = 1;
  for (let x = 0; x <= 10; x += 1) {
    ctx.beginPath();
    ctx.moveTo(toCanvasX(x), toCanvasY(-3));
    ctx.lineTo(toCanvasX(x), toCanvasY(3));
    ctx.stroke();
  }
  for (let y = -3; y <= 3; y += 1) {
    ctx.beginPath();
    ctx.moveTo(toCanvasX(0), toCanvasY(y));
    ctx.lineTo(toCanvasX(10), toCanvasY(y));
    ctx.stroke();
  }

  // 2. Room Boundary
  ctx.strokeStyle = '#3b506e';
  ctx.lineWidth = 3;
  ctx.fillStyle = '#0a0e17';
  ctx.beginPath();
  manifest.geometry.boundary.forEach(([x, y], idx) => {
    if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
    else ctx.lineTo(toCanvasX(x), toCanvasY(y));
  });
  ctx.closePath();
  ctx.fill();
  ctx.stroke();

  // 3. Polyline Route
  ctx.strokeStyle = '#23384d';
  ctx.lineWidth = 3;
  ctx.setLineDash([6, 6]);
  ctx.beginPath();
  manifest.geometry.route.waypoints.forEach(([x, y], idx) => {
    if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
    else ctx.lineTo(toCanvasX(x), toCanvasY(y));
  });
  ctx.stroke();
  ctx.setLineDash([]);

  // 4. Ghosted Alternate Obstacle Outline
  const repair = manifest.repair;
  const ghostObstacles = currentMode === 'broken'
    ? manifest.geometry.obstacles.map(obs => {
        if (obs.obstacle_id === repair.obstacle_id) {
          const dx = repair.direction[0] * repair.displacement_m;
          const dy = repair.direction[1] * repair.displacement_m;
          return { vertices: obs.vertices.map(([x, y]) => [x + dx, y + dy]) };
        }
        return null;
      }).filter(Boolean)
    : manifest.geometry.obstacles;

  ghostObstacles.forEach(obs => {
    ctx.strokeStyle = currentMode === 'broken' ? 'rgba(63, 185, 80, 0.4)' : 'rgba(248, 81, 73, 0.4)';
    ctx.lineWidth = 1.5;
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    obs.vertices.forEach(([x, y], idx) => {
      if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
      else ctx.lineTo(toCanvasX(x), toCanvasY(y));
    });
    ctx.closePath();
    ctx.stroke();
    ctx.setLineDash([]);
  });

  // 5. Active Obstacles
  const activeObstacles = getObstacles();
  activeObstacles.forEach(obs => {
    ctx.fillStyle = currentMode === 'broken' ? '#1c2536' : '#142d2a';
    ctx.strokeStyle = currentMode === 'broken' ? '#4f688a' : '#3fb950';
    ctx.lineWidth = 2;

    ctx.beginPath();
    obs.vertices.forEach(([x, y], idx) => {
      if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
      else ctx.lineTo(toCanvasX(x), toCanvasY(y));
    });
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
  });

  // Highlight Controlling Occluder Edge in Broken Mode
  if (currentMode === 'broken' && manifest.broken_scenario.diagnostic && manifest.broken_scenario.diagnostic.controlling_occluder_segment) {
    const seg = manifest.broken_scenario.diagnostic.controlling_occluder_segment;
    ctx.strokeStyle = '#d29922';
    ctx.lineWidth = 4;
    ctx.beginPath();
    ctx.moveTo(toCanvasX(seg[0][0]), toCanvasY(seg[0][1]));
    ctx.lineTo(toCanvasX(seg[1][0]), toCanvasY(seg[1][1]));
    ctx.stroke();
  }

  // 6. Threats
  manifest.geometry.threats.forEach(threat => {
    const isVisible = currentFrame.visible_threat_ids.includes(threat.id);
    const isTarget = currentFrame.active_target_id === threat.id;
    
    // Draw threat bounding box
    ctx.fillStyle = isVisible ? 'rgba(248, 81, 73, 0.25)' : 'rgba(248, 81, 73, 0.08)';
    ctx.strokeStyle = isVisible ? '#f85149' : '#5c2528';
    ctx.lineWidth = isTarget ? 3 : 1.5;

    ctx.beginPath();
    threat.polygon.forEach(([x, y], idx) => {
      if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
      else ctx.lineTo(toCanvasX(x), toCanvasY(y));
    });
    ctx.closePath();
    ctx.fill();
    ctx.stroke();

    // Threat Anchor
    const ax = toCanvasX(threat.anchor[0]);
    const ay = toCanvasY(threat.anchor[1]);
    ctx.fillStyle = isVisible ? '#f85149' : '#8b3a3e';
    ctx.beginPath();
    ctx.arc(ax, ay, 6, 0, Math.PI * 2);
    ctx.fill();

    // Label
    ctx.fillStyle = '#f0f6fc';
    ctx.font = 'bold 11px monospace';
    ctx.fillText(threat.id, ax - 20, ay - 12);
  });

  // 7. LOS Rays from Player
  const px = toCanvasX(currentFrame.player_pos[0]);
  const py = toCanvasY(currentFrame.player_pos[1]);

  currentFrame.los_rays.forEach(ray => {
    const tx = toCanvasX(ray.target_pos[0]);
    const ty = toCanvasY(ray.target_pos[1]);

    if (ray.is_visible) {
      ctx.strokeStyle = currentFrame.active_target_id === ray.threat_id ? '#3fb950' : 'rgba(88, 166, 255, 0.6)';
      ctx.lineWidth = currentFrame.active_target_id === ray.threat_id ? 2.5 : 1;
      ctx.setLineDash([]);
    } else {
      ctx.strokeStyle = 'rgba(248, 81, 73, 0.2)';
      ctx.lineWidth = 1;
      ctx.setLineDash([4, 4]);
    }

    ctx.beginPath();
    ctx.moveTo(px, py);
    ctx.lineTo(tx, ty);
    ctx.stroke();
    ctx.setLineDash([]);
  });

  // 8. Player Body and Aim Laser
  // View Cone
  const fwdAngleRad = (currentFrame.forward_heading_deg * Math.PI) / 180.0;
  const reticleAngleRad = (currentFrame.reticle_heading_deg * Math.PI) / 180.0;
  const fovRad = (90 * Math.PI) / 180.0;

  ctx.fillStyle = 'rgba(88, 166, 255, 0.08)';
  ctx.beginPath();
  ctx.moveTo(px, py);
  ctx.arc(px, py, 140, -reticleAngleRad - fovRad / 2, -reticleAngleRad + fovRad / 2);
  ctx.closePath();
  ctx.fill();

  // Reticle Laser Pointer
  const laserLen = 220;
  const lx = px + Math.cos(reticleAngleRad) * laserLen;
  const ly = py - Math.sin(reticleAngleRad) * laserLen; // flip y for canvas

  ctx.strokeStyle = currentFrame.controller_state === 'SERVICING' ? '#ffd33d' : '#58a6ff';
  ctx.lineWidth = currentFrame.controller_state === 'SERVICING' ? 3 : 2;
  ctx.beginPath();
  ctx.moveTo(px, py);
  ctx.lineTo(lx, ly);
  ctx.stroke();

  // Player Circle
  const isDead = currentFrame.controller_state === 'DEAD';
  ctx.fillStyle = isDead ? '#f85149' : '#58a6ff';
  ctx.strokeStyle = '#ffffff';
  ctx.lineWidth = 2.5;
  ctx.beginPath();
  ctx.arc(px, py, 9, 0, Math.PI * 2);
  ctx.fill();
  ctx.stroke();

  // Forward Heading Pointer
  const hx = px + Math.cos(fwdAngleRad) * 16;
  const hy = py - Math.sin(fwdAngleRad) * 16;
  ctx.strokeStyle = '#ffffff';
  ctx.lineWidth = 2;
  ctx.beginPath();
  ctx.moveTo(px, py);
  ctx.lineTo(hx, hy);
  ctx.stroke();
}

// Start application
window.addEventListener('DOMContentLoaded', init);
