/**
 * Tactical CAD (Cut the Cake) - Milestone 1B Telemetry Playback Engine
 * 
 * Strict boundary:
 * - Browser is a dumb renderer for scientific telemetry.
 * - Does NOT calculate tactical margins, does NOT raycast, does NOT repair geometry.
 * - Renders authoritative 35 Hz per-tic states generated by the frozen Python scientific core.
 */

// State
let manifest = null;
let currentMode = 'broken'; // 'broken' | 'repaired'
let currentTic = 0;
let isPlaying = false;
let playbackSpeed = 1.0;
let animTimer = null;

// DOM Elements
const canvas = document.getElementById('mapCanvas');
const ctx = canvas.getContext('2d');
const viewportContainer = document.getElementById('viewportContainer');

const btnModeBroken = document.getElementById('btnModeBroken');
const btnModeRepaired = document.getElementById('btnModeRepaired');
const btnPlayPause = document.getElementById('btnPlayPause');
const btnStepBack = document.getElementById('btnStepBack');
const btnStepFwd = document.getElementById('btnStepFwd');
const btnReset = document.getElementById('btnReset');
const btnSpeed05 = document.getElementById('btnSpeed05');
const btnSpeed10 = document.getElementById('btnSpeed10');
const btnSpeed20 = document.getElementById('btnSpeed20');
const btnJumpBottleneck = document.getElementById('btnJumpBottleneck');

const timelineScrubber = document.getElementById('timelineScrubber');
const timelineProgress = document.getElementById('timelineProgress');
const timelineHead = document.getElementById('timelineHead');
const eventMarkerLayer = document.getElementById('eventMarkerLayer');

const readoutTic = document.getElementById('readoutTic');
const readoutTotalTics = document.getElementById('readoutTotalTics');
const readoutTime = document.getElementById('readoutTime');
const readoutTotalTime = document.getElementById('readoutTotalTime');

const fixtureBadge = document.getElementById('fixtureBadge');
const evidenceBadge = document.getElementById('evidenceBadge');
const verdictBadge = document.getElementById('verdictBadge');
const valMargin = document.getElementById('valMargin');
const valMarginMs = document.getElementById('valMarginMs');
const valLStar = document.getElementById('valLStar');
const valEngineStatus = document.getElementById('valEngineStatus');
const valEngineResidual = document.getElementById('valEngineResidual');
const controllerStateBadge = document.getElementById('controllerStateBadge');
const valActiveTarget = document.getElementById('valActiveTarget');
const valRouteDist = document.getElementById('valRouteDist');
const valMoveSpeed = document.getElementById('valMoveSpeed');
const valSlewSpeed = document.getElementById('valSlewSpeed');

const threatListContainer = document.getElementById('threatListContainer');
const whyCard = document.getElementById('whyCard');
const whyText = document.getElementById('whyText');
const repairCard = document.getElementById('repairCard');
const repairText = document.getElementById('repairText');

const tagPlayerPos = document.getElementById('tagPlayerPos');
const tagReticle = document.getElementById('tagReticle');
const tagLOS = document.getElementById('tagLOS');

// What Changed elements
const wcT1Broken = document.getElementById('wcT1Broken');
const wcT1Repaired = document.getElementById('wcT1Repaired');
const wcT2Broken = document.getElementById('wcT2Broken');
const wcT2Repaired = document.getElementById('wcT2Repaired');
const wcGapBroken = document.getElementById('wcGapBroken');
const wcGapRepaired = document.getElementById('wcGapRepaired');
const wcMarginBroken = document.getElementById('wcMarginBroken');
const wcMarginRepaired = document.getElementById('wcMarginRepaired');
const wcShift = document.getElementById('wcShift');

// Dynamic Coordinate Transformation (Meters -> Canvas Pixels)
let viewTransform = {
  scale: 60,
  offsetX: 80,
  offsetY: 250,
  minX: 0,
  maxX: 10,
  minY: -3,
  maxY: 3
};

// Initialize Application
async function init() {
  try {
    if (window.SCENE_MANIFEST) {
      manifest = window.SCENE_MANIFEST;
    } else {
      const resp = await fetch('../data/m1_scene.json');
      manifest = await resp.json();
    }
    setupDynamicBounds();
    setupUI();
    setupCanvas();
    renderTimelineEvents();
    populateWhatChangedCard();
    updateView(0);
  } catch (err) {
    console.error('Failed to load scene manifest:', err);
    alert('Failed to load Tactical CAD scene manifest: ' + err.message);
  }
}

function getGeometry() {
  return currentMode === 'broken' ? manifest.broken_geometry : manifest.repaired_geometry;
}

function getScenario() {
  return currentMode === 'broken' ? manifest.broken_scenario : manifest.repaired_scenario;
}

function setupDynamicBounds() {
  const boundary = manifest.broken_geometry.boundary;
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  
  boundary.forEach(([x, y]) => {
    minX = Math.min(minX, x);
    maxX = Math.max(maxX, x);
    minY = Math.min(minY, y);
    maxY = Math.max(maxY, y);
  });

  manifest.broken_geometry.threats.forEach(t => {
    t.polygon.forEach(([x, y]) => {
      minX = Math.min(minX, x);
      maxX = Math.max(maxX, x);
      minY = Math.min(minY, y);
      maxY = Math.max(maxY, y);
    });
  });

  viewTransform.minX = minX;
  viewTransform.maxX = maxX;
  viewTransform.minY = minY;
  viewTransform.maxY = maxY;
}

function populateWhatChangedCard() {
  const bJobs = manifest.broken_scenario.threat_jobs;
  const rJobs = manifest.repaired_scenario.threat_jobs;
  const repair = manifest.repair;
  const dt = manifest.clock.dt_s;

  const t1B = bJobs[0];
  const t1R = rJobs[0];
  const t2B = bJobs[1];
  const t2R = rJobs[1];

  wcT1Broken.textContent = `Tic ${t1B.reveal_tic} (${(t1B.reveal_tic * dt).toFixed(2)}s)`;
  wcT1Repaired.textContent = `Tic ${t1R.reveal_tic} (${(t1R.reveal_tic * dt).toFixed(2)}s)`;

  wcT2Broken.textContent = `Tic ${t2B.reveal_tic} (${(t2B.reveal_tic * dt).toFixed(2)}s)`;
  const t2DeltaTics = t2R.reveal_tic - t2B.reveal_tic;
  const t2DeltaMs = Math.round(t2DeltaTics * dt * 1000);
  wcT2Repaired.textContent = `Tic ${t2R.reveal_tic} (${(t2R.reveal_tic * dt).toFixed(2)}s) [Delayed +${t2DeltaTics}t / +${t2DeltaMs}ms]`;

  const gapB = Math.round((t2B.reveal_tic - t1B.reveal_tic) * dt * 1000);
  const gapR = Math.round((t2R.reveal_tic - t1R.reveal_tic) * dt * 1000);
  wcGapBroken.textContent = `${gapB} ms`;
  wcGapRepaired.textContent = `${gapR} ms (+${gapR - gapB}ms)`;

  wcMarginBroken.textContent = `${manifest.broken_scenario.tactical_margin_tics} tics (${manifest.broken_scenario.tactical_margin_ms}ms)`;
  wcMarginRepaired.textContent = `+${manifest.repaired_scenario.tactical_margin_tics} tics (+${manifest.repaired_scenario.tactical_margin_ms}ms)`;

  wcShift.textContent = `+${repair.displacement_m.toFixed(2)} m (${repair.direction[0] >= 0 ? '+x' : '-x'})`;
}

function setupUI() {
  fixtureBadge.textContent = manifest.provenance.fixture_id;
  evidenceBadge.textContent = manifest.external_engine_evidence.evidence_tier === 'native_engine_verified'
    ? 'EXTERNAL: NATIVE VIZDOOM VERIFIED'
    : 'SOURCE MODEL PLAYBACK';

  readoutTotalTics.textContent = manifest.clock.total_tics;
  readoutTotalTime.textContent = manifest.clock.total_duration_s.toFixed(2) + 's';

  const vMove = manifest.source_parameters.v_move_mps;
  const movePerTic = (vMove / manifest.clock.ticrate_hz).toFixed(3);
  valMoveSpeed.textContent = `${vMove.toFixed(1)} m/s (${movePerTic} m/tic)`;

  const wSlew = manifest.source_parameters.omega_slew_deg_per_s;
  const slewPerTic = (wSlew / manifest.clock.ticrate_hz).toFixed(2);
  valSlewSpeed.textContent = `${wSlew.toFixed(0)}°/s (${slewPerTic}°/tic)`;

  // Mode Toggle Events
  btnModeBroken.addEventListener('click', () => switchMode('broken'));
  btnModeRepaired.addEventListener('click', () => switchMode('repaired'));

  // Playback Controls
  btnPlayPause.addEventListener('click', togglePlay);
  btnStepBack.addEventListener('click', () => stepTic(-1));
  btnStepFwd.addEventListener('click', () => stepTic(1));
  btnReset.addEventListener('click', () => setTic(0));

  // Jump to Bottleneck
  btnJumpBottleneck.addEventListener('click', () => {
    if (currentMode === 'broken') {
      const bJobs = manifest.broken_scenario.threat_jobs;
      setTic(bJobs[1] ? bJobs[1].reveal_tic : 3);
    } else {
      const rJobs = manifest.repaired_scenario.threat_jobs;
      setTic(rJobs[1] ? rJobs[1].reveal_tic : 13);
    }
  });

  // Speed Controls
  btnSpeed05.addEventListener('click', () => setSpeed(0.5, btnSpeed05));
  btnSpeed10.addEventListener('click', () => setSpeed(1.0, btnSpeed10));
  btnSpeed20.addEventListener('click', () => setSpeed(2.0, btnSpeed20));

  // Timeline Scrubbing
  timelineScrubber.addEventListener('click', (e) => {
    const rect = timelineScrubber.getBoundingClientRect();
    const ratio = Math.max(0, Math.min(1, (e.clientX - rect.left) / rect.width));
    const targetTic = Math.round(ratio * manifest.clock.total_tics);
    setTic(targetTic);
  });

  window.addEventListener('resize', resizeCanvas);
}

function switchMode(mode) {
  currentMode = mode;
  if (mode === 'broken') {
    btnModeBroken.className = 'toggle-btn active broken';
    btnModeRepaired.className = 'toggle-btn';
    repairCard.style.display = 'none';
    whyCard.style.display = 'block';
    const bJobs = manifest.broken_scenario.threat_jobs;
    btnJumpBottleneck.textContent = `⚡ Jump to Critical Bottleneck (Tic ${bJobs[1] ? bJobs[1].reveal_tic : 3})`;
  } else {
    btnModeBroken.className = 'toggle-btn';
    btnModeRepaired.className = 'toggle-btn active repaired';
    repairCard.style.display = 'block';
    whyCard.style.display = 'none';
    const rJobs = manifest.repaired_scenario.threat_jobs;
    btnJumpBottleneck.textContent = `⚡ Jump to Delayed Reveal (Tic ${rJobs[1] ? rJobs[1].reveal_tic : 13})`;
  }
  renderTimelineEvents();
  updateView(currentTic);
}

function setSpeed(speed, activeBtn) {
  playbackSpeed = speed;
  [btnSpeed05, btnSpeed10, btnSpeed20].forEach(b => b.style.background = '#172130');
  activeBtn.style.background = '#233145';
  if (isPlaying) {
    pause();
    play();
  }
}

function togglePlay() {
  if (isPlaying) {
    pause();
  } else {
    play();
  }
}

function play() {
  const scenario = getScenario();
  if (currentTic >= scenario.telemetry_frames.length - 1) {
    currentTic = 0;
  }
  isPlaying = true;
  btnPlayPause.textContent = '⏸ Pause';
  btnPlayPause.classList.remove('primary');
  btnPlayPause.style.background = 'var(--amber)';

  const intervalMs = (1000.0 / manifest.clock.ticrate_hz) / playbackSpeed;
  animTimer = setInterval(() => {
    if (currentTic < scenario.telemetry_frames.length - 1) {
      setTic(currentTic + 1);
    } else {
      pause();
    }
  }, intervalMs);
}

function pause() {
  isPlaying = false;
  clearInterval(animTimer);
  btnPlayPause.textContent = '▶ Play';
  btnPlayPause.classList.add('primary');
  btnPlayPause.style.background = '';
}

function stepTic(delta) {
  pause();
  const scenario = getScenario();
  const maxTic = scenario.telemetry_frames.length - 1;
  const nextTic = Math.max(0, Math.min(maxTic, currentTic + delta));
  setTic(nextTic);
}

function setTic(tic) {
  currentTic = tic;
  updateView(tic);
}

function setupCanvas() {
  resizeCanvas();
}

function resizeCanvas() {
  const rect = viewportContainer.getBoundingClientRect();
  canvas.width = rect.width - 20;
  canvas.height = rect.height - 20;
  
  const spanX = (viewTransform.maxX - viewTransform.minX) + 1.0;
  const spanY = (viewTransform.maxY - viewTransform.minY) + 1.0;
  
  const padding = 55;
  const scaleX = (canvas.width - padding * 2) / spanX;
  const scaleY = (canvas.height - padding * 2) / spanY;
  viewTransform.scale = Math.min(scaleX, scaleY);
  
  viewTransform.offsetX = padding + 15 - (viewTransform.minX * viewTransform.scale);
  viewTransform.offsetY = canvas.height / 2;
  
  drawMap();
}

// Convert arena coordinates (m) to canvas pixels
function toCanvasX(x) {
  return viewTransform.offsetX + x * viewTransform.scale;
}

function toCanvasY(y) {
  // Arena +y is up, canvas +y is down
  return viewTransform.offsetY - y * viewTransform.scale;
}

// Render Timeline Events
function renderTimelineEvents() {
  eventMarkerLayer.innerHTML = '';
  const scenario = getScenario();
  const totalTics = manifest.clock.total_tics;

  scenario.events.forEach(evt => {
    const marker = document.createElement('div');
    marker.className = 'event-marker ' + evt.type.toLowerCase().replace('_', '-');
    const pct = (evt.tic / totalTics) * 100;
    marker.style.left = `${pct}%`;
    marker.title = `[Tic ${evt.tic} / ${evt.time_s}s] ${evt.type}: ${evt.description}`;
    marker.addEventListener('click', (e) => {
      e.stopPropagation();
      setTic(evt.tic);
    });
    eventMarkerLayer.appendChild(marker);
  });
}

// Main View Update
function updateView(tic) {
  const scenario = getScenario();
  const frames = scenario.telemetry_frames;
  const frame = frames[Math.min(tic, frames.length - 1)];

  // Update Timeline Scrubber
  const totalTics = manifest.clock.total_tics;
  const progressPct = (frame.tic / totalTics) * 100;
  timelineProgress.style.width = `${progressPct}%`;
  timelineHead.style.left = `${progressPct}%`;

  // Update Header Readouts
  readoutTic.textContent = frame.tic;
  readoutTime.textContent = frame.time_s.toFixed(2) + 's';

  // Update Sidebar
  if (currentMode === 'broken') {
    verdictBadge.textContent = 'UNSERVICEABLE';
    verdictBadge.className = 'badge';
    verdictBadge.style.color = 'var(--red)';
    verdictBadge.style.borderColor = 'rgba(248, 81, 73, 0.4)';
    
    valMargin.textContent = `${scenario.tactical_margin_tics} tics`;
    valMargin.className = 'margin-val status-unserviceable';
    valMarginMs.textContent = `${scenario.tactical_margin_ms} ms`;
    valMarginMs.className = 'margin-status status-unserviceable';
    
    valLStar.textContent = `+${scenario.l_star_tics} tics (Late)`;
    valEngineStatus.textContent = `Fatal Death (0 HP)`;
    valEngineStatus.style.color = 'var(--red)';
    valEngineResidual.textContent = `${manifest.external_engine_evidence.delta_total_tics} tics (Zero Drift)`;
  } else {
    verdictBadge.textContent = 'SERVICEABLE';
    verdictBadge.className = 'badge verified';
    
    valMargin.textContent = `+${scenario.tactical_margin_tics} tics`;
    valMargin.className = 'margin-val status-serviceable';
    valMarginMs.textContent = `+${scenario.tactical_margin_ms} ms`;
    valMarginMs.className = 'margin-status status-serviceable';
    
    valLStar.textContent = `${scenario.l_star_tics} tics (On Time)`;
    valEngineStatus.textContent = `Rescued / Survived (100 HP)`;
    valEngineStatus.style.color = 'var(--green)';
    valEngineResidual.textContent = `${manifest.external_engine_evidence.delta_total_tics} tics (Zero Drift)`;
  }

  // Controller State
  controllerStateBadge.textContent = frame.controller_state;
  if (frame.controller_state === 'DEAD') {
    controllerStateBadge.style.background = 'rgba(248, 81, 73, 0.2)';
    controllerStateBadge.style.color = 'var(--red)';
  } else if (frame.controller_state === 'CLEARED') {
    controllerStateBadge.style.background = 'rgba(63, 185, 80, 0.2)';
    controllerStateBadge.style.color = 'var(--green)';
  } else if (frame.controller_state === 'SERVICING') {
    controllerStateBadge.style.background = 'rgba(210, 153, 34, 0.2)';
    controllerStateBadge.style.color = 'var(--amber)';
  } else {
    controllerStateBadge.style.background = '#172030';
    controllerStateBadge.style.color = 'var(--blue)';
  }

  const actJob = scenario.threat_jobs.find(j => j.id === frame.active_target_id);
  valActiveTarget.textContent = actJob ? `${actJob.label} (${actJob.id})` : 'None';
  valRouteDist.textContent = `${frame.route_dist_m.toFixed(2)} m / ${getGeometry().route.total_length_m.toFixed(2)} m`;

  // Overlay Tags
  tagPlayerPos.textContent = `POS: (${frame.player_pos[0].toFixed(2)}m, ${frame.player_pos[1].toFixed(2)}m)`;
  tagReticle.textContent = `RETICLE: ${frame.reticle_heading_deg.toFixed(1)}° (FWD: ${frame.forward_heading_deg.toFixed(1)}°)`;
  tagLOS.textContent = `VISIBLE: ${frame.visible_threat_ids.length} [${frame.visible_threat_ids.join(', ')}]`;

  // Threats List
  renderThreatList(frame);

  // Diagnostic Cards
  if (scenario.diagnostic) {
    whyText.textContent = scenario.diagnostic.explanation;
  }
  if (manifest.repair) {
    repairText.textContent = `${manifest.repair.description} (Shift: ${manifest.repair.displacement_m.toFixed(2)}m, Invariants Validated: ${manifest.repair.preservation_validated ? 'YES' : 'NO'}).`;
  }

  // Render Map Canvas
  drawMap(frame);
}

function renderThreatList(currentFrame) {
  const scenario = getScenario();
  threatListContainer.innerHTML = '';

  scenario.threat_jobs.forEach(job => {
    const isVisible = currentFrame.visible_threat_ids.includes(job.id);
    const isTarget = currentFrame.active_target_id === job.id;
    const isCleared = currentFrame.tic >= job.service_complete_tic && scenario.model_episode_survived;
    const isBreached = currentFrame.tic >= job.deadline_tic && !isCleared;

    let statusTag = 'Occluded';
    let statusColor = 'var(--text-muted)';
    let itemClass = 'threat-item';

    if (isCleared) {
      statusTag = `Neutralized (Tic ${job.service_complete_tic})`;
      statusColor = 'var(--green)';
      itemClass += ' neutralized';
    } else if (isBreached) {
      statusTag = `BREACHED (+${job.lateness_tics} tics)`;
      statusColor = 'var(--red)';
    } else if (isTarget && currentFrame.controller_state === 'SERVICING') {
      statusTag = 'ENGAGING / FIRING';
      statusColor = 'var(--amber)';
    } else if (isTarget) {
      statusTag = 'ACQUIRING / AIMING';
      statusColor = 'var(--blue)';
    } else if (isVisible) {
      statusTag = `Revealed (Due Tic ${job.deadline_tic})`;
      statusColor = 'var(--blue)';
    }

    const item = document.createElement('div');
    item.className = itemClass;
    item.innerHTML = `
      <div>
        <div class="threat-name">
          <div class="threat-pill" style="background: ${statusColor};"></div>
          <span>${job.label}</span>
          <span class="threat-sublabel">${job.id}</span>
        </div>
        <div class="threat-timing">
          r=${job.reveal_tic} | D=${job.deadline_tic} | Angle: ${job.angle_deg}°
        </div>
      </div>
      <div class="threat-status-tag" style="color: ${statusColor};">${statusTag}</div>
    `;
    threatListContainer.appendChild(item);
  });
}

// 2D Canvas Map Drawing
function drawMap(frame) {
  if (!manifest) return;
  const currentFrame = frame || getScenario().telemetry_frames[Math.min(currentTic, getScenario().telemetry_frames.length - 1)];
  const currentGeo = getGeometry();

  ctx.clearRect(0, 0, canvas.width, canvas.height);

  // 1. Draw Grid in Meters
  ctx.strokeStyle = '#121926';
  ctx.lineWidth = 1;
  const minX = Math.floor(viewTransform.minX);
  const maxX = Math.ceil(viewTransform.maxX);
  const minY = Math.floor(viewTransform.minY);
  const maxY = Math.ceil(viewTransform.maxY);

  for (let x = minX; x <= maxX; x += 1) {
    ctx.beginPath();
    ctx.moveTo(toCanvasX(x), toCanvasY(minY));
    ctx.lineTo(toCanvasX(x), toCanvasY(maxY));
    ctx.stroke();
  }
  for (let y = minY; y <= maxY; y += 1) {
    ctx.beginPath();
    ctx.moveTo(toCanvasX(minX), toCanvasY(y));
    ctx.lineTo(toCanvasX(maxX), toCanvasY(y));
    ctx.stroke();
  }

  // 2. Room Boundary
  ctx.strokeStyle = '#3b506e';
  ctx.lineWidth = 3;
  ctx.fillStyle = '#0a0e17';
  ctx.beginPath();
  currentGeo.boundary.forEach(([x, y], idx) => {
    if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
    else ctx.lineTo(toCanvasX(x), toCanvasY(y));
  });
  ctx.closePath();
  ctx.fill();
  ctx.stroke();

  // 3. Polyline Route
  ctx.strokeStyle = '#23384d';
  ctx.lineWidth = 3;
  ctx.setLineDash([6, 6]);
  ctx.beginPath();
  currentGeo.route.waypoints.forEach(([x, y], idx) => {
    if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
    else ctx.lineTo(toCanvasX(x), toCanvasY(y));
  });
  ctx.stroke();
  ctx.setLineDash([]);

  // 4. Ghosted Alternate Obstacle Outline & Translation Arrow in Repaired Mode
  if (currentMode === 'repaired') {
    const ghostObstacles = manifest.broken_geometry.obstacles;
    ghostObstacles.forEach(obs => {
      ctx.strokeStyle = 'rgba(248, 81, 73, 0.4)';
      ctx.lineWidth = 1.5;
      ctx.setLineDash([4, 4]);
      ctx.beginPath();
      obs.vertices.forEach(([x, y], idx) => {
        if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
        else ctx.lineTo(toCanvasX(x), toCanvasY(y));
      });
      ctx.closePath();
      ctx.stroke();
      ctx.setLineDash([]);
    });

    // Draw Causal Translation Arrow from old obstacle to new obstacle
    const oldObs = manifest.broken_geometry.obstacles[manifest.repair.obstacle_id];
    const newObs = manifest.repaired_geometry.obstacles[manifest.repair.obstacle_id];
    if (oldObs && newObs) {
      const oldX = (oldObs.vertices[0][0] + oldObs.vertices[1][0]) / 2;
      const oldY = (oldObs.vertices[0][1] + oldObs.vertices[2][1]) / 2;
      const newX = (newObs.vertices[0][0] + newObs.vertices[1][0]) / 2;
      const newY = (newObs.vertices[0][1] + newObs.vertices[2][1]) / 2;

      const p1x = toCanvasX(oldX);
      const p1y = toCanvasY(oldY);
      const p2x = toCanvasX(newX);
      const p2y = toCanvasY(newY);

      // Arrow line
      ctx.strokeStyle = '#3fb950';
      ctx.lineWidth = 2.5;
      ctx.beginPath();
      ctx.moveTo(p1x, p1y);
      ctx.lineTo(p2x, p2y);
      ctx.stroke();

      // Arrow head
      const angle = Math.atan2(p2y - p1y, p2x - p1x);
      const headLen = 10;
      ctx.fillStyle = '#3fb950';
      ctx.beginPath();
      ctx.moveTo(p2x, p2y);
      ctx.lineTo(p2x - headLen * Math.cos(angle - Math.PI / 6), p2y - headLen * Math.sin(angle - Math.PI / 6));
      ctx.lineTo(p2x - headLen * Math.cos(angle + Math.PI / 6), p2y - headLen * Math.sin(angle + Math.PI / 6));
      ctx.closePath();
      ctx.fill();

      // Label
      ctx.fillStyle = '#3fb950';
      ctx.font = 'bold 11px monospace';
      ctx.fillText(`+${manifest.repair.displacement_m.toFixed(2)}m (Baffle Shift)`, (p1x + p2x) / 2 - 40, p1y - 14);
    }
  }

  // 5. Active Obstacles
  currentGeo.obstacles.forEach(obs => {
    ctx.fillStyle = currentMode === 'broken' ? '#1c2536' : '#142d2a';
    ctx.strokeStyle = currentMode === 'broken' ? '#4f688a' : '#3fb950';
    ctx.lineWidth = 2;

    ctx.beginPath();
    obs.vertices.forEach(([x, y], idx) => {
      if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
      else ctx.lineTo(toCanvasX(x), toCanvasY(y));
    });
    ctx.closePath();
    ctx.fill();
    ctx.stroke();
  });

  // Highlight Controlling Occluder Edge in Broken Mode
  if (currentMode === 'broken' && manifest.broken_scenario.diagnostic && manifest.broken_scenario.diagnostic.controlling_occluder_segment) {
    const seg = manifest.broken_scenario.diagnostic.controlling_occluder_segment;
    ctx.strokeStyle = '#d29922';
    ctx.lineWidth = 4;
    ctx.beginPath();
    ctx.moveTo(toCanvasX(seg[0][0]), toCanvasY(seg[0][1]));
    ctx.lineTo(toCanvasX(seg[1][0]), toCanvasY(seg[1][1]));
    ctx.stroke();
  }

  // 6. Threats
  const scenario = getScenario();
  currentGeo.threats.forEach(threat => {
    const isVisible = currentFrame.visible_threat_ids.includes(threat.id);
    const isTarget = currentFrame.active_target_id === threat.id;
    const job = scenario.threat_jobs.find(j => j.id === threat.id);
    const isNeutralized = job && currentFrame.tic >= job.service_complete_tic && scenario.model_episode_survived;

    // Draw threat bounding box
    if (isNeutralized) {
      ctx.fillStyle = 'rgba(63, 185, 80, 0.1)';
      ctx.strokeStyle = '#238636';
      ctx.lineWidth = 1.5;
    } else if (isVisible) {
      ctx.fillStyle = isTarget ? 'rgba(248, 81, 73, 0.35)' : 'rgba(248, 81, 73, 0.2)';
      ctx.strokeStyle = '#f85149';
      ctx.lineWidth = isTarget ? 3 : 1.5;
    } else {
      ctx.fillStyle = 'rgba(88, 166, 255, 0.05)';
      ctx.strokeStyle = '#2a3a4f';
      ctx.lineWidth = 1;
    }

    ctx.beginPath();
    threat.polygon.forEach(([x, y], idx) => {
      if (idx === 0) ctx.moveTo(toCanvasX(x), toCanvasY(y));
      else ctx.lineTo(toCanvasX(x), toCanvasY(y));
    });
    ctx.closePath();
    ctx.fill();
    ctx.stroke();

    // Threat Anchor
    const ax = toCanvasX(threat.anchor[0]);
    const ay = toCanvasY(threat.anchor[1]);
    ctx.fillStyle = isNeutralized ? '#3fb950' : (isVisible ? '#f85149' : '#3b4b5e');
    ctx.beginPath();
    ctx.arc(ax, ay, 6, 0, Math.PI * 2);
    ctx.fill();

    // Label
    ctx.fillStyle = isNeutralized ? '#3fb950' : '#f0f6fc';
    ctx.font = 'bold 11px monospace';
    const displayTag = isNeutralized ? `✓ ${threat.label}` : threat.label;
    ctx.fillText(displayTag, ax - 24, ay - 12);
  });

  // 7. LOS Rays from Player
  const px = toCanvasX(currentFrame.player_pos[0]);
  const py = toCanvasY(currentFrame.player_pos[1]);

  currentFrame.los_rays.forEach(ray => {
    const tx = toCanvasX(ray.target_pos[0]);
    const ty = toCanvasY(ray.target_pos[1]);
    const job = scenario.threat_jobs.find(j => j.id === ray.threat_id);
    const isNeutralized = job && currentFrame.tic >= job.service_complete_tic && scenario.model_episode_survived;

    if (ray.is_visible && !isNeutralized) {
      ctx.strokeStyle = currentFrame.active_target_id === ray.threat_id ? '#3fb950' : 'rgba(88, 166, 255, 0.6)';
      ctx.lineWidth = currentFrame.active_target_id === ray.threat_id ? 2.5 : 1;
      ctx.setLineDash([]);
    } else {
      ctx.strokeStyle = 'rgba(255, 255, 255, 0.08)';
      ctx.lineWidth = 1;
      ctx.setLineDash([4, 4]);
    }

    ctx.beginPath();
    ctx.moveTo(px, py);
    ctx.lineTo(tx, ty);
    ctx.stroke();
    ctx.setLineDash([]);
  });

  // 8. Player Body and Aim Laser
  const isDead = currentFrame.controller_state === 'DEAD';
  const fwdAngleRad = (currentFrame.forward_heading_deg * Math.PI) / 180.0;
  const reticleAngleRad = (currentFrame.reticle_heading_deg * Math.PI) / 180.0;
  const fovRad = (90 * Math.PI) / 180.0;

  if (!isDead) {
    // View Cone
    ctx.fillStyle = 'rgba(88, 166, 255, 0.08)';
    ctx.beginPath();
    ctx.moveTo(px, py);
    ctx.arc(px, py, 140, -reticleAngleRad - fovRad / 2, -reticleAngleRad + fovRad / 2);
    ctx.closePath();
    ctx.fill();

    // Reticle Laser Pointer
    const laserLen = 220;
    const lx = px + Math.cos(reticleAngleRad) * laserLen;
    const ly = py - Math.sin(reticleAngleRad) * laserLen;

    ctx.strokeStyle = currentFrame.controller_state === 'SERVICING' ? '#ffd33d' : '#58a6ff';
    ctx.lineWidth = currentFrame.controller_state === 'SERVICING' ? 3 : 2;
    ctx.beginPath();
    ctx.moveTo(px, py);
    ctx.lineTo(lx, ly);
    ctx.stroke();
  }

  // Player Circle
  ctx.fillStyle = isDead ? '#f85149' : '#58a6ff';
  ctx.strokeStyle = '#ffffff';
  ctx.lineWidth = 2.5;
  ctx.beginPath();
  ctx.arc(px, py, 9, 0, Math.PI * 2);
  ctx.fill();
  ctx.stroke();

  if (isDead) {
    // Cross marker on dead player
    ctx.strokeStyle = '#ffffff';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(px - 5, py - 5);
    ctx.lineTo(px + 5, py + 5);
    ctx.moveTo(px + 5, py - 5);
    ctx.lineTo(px - 5, py + 5);
    ctx.stroke();
  } else {
    // Forward Heading Pointer
    const hx = px + Math.cos(fwdAngleRad) * 16;
    const hy = py - Math.sin(fwdAngleRad) * 16;
    ctx.strokeStyle = '#ffffff';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(px, py);
    ctx.lineTo(hx, hy);
    ctx.stroke();
  }
}

// Start application
window.addEventListener('DOMContentLoaded', init);
